#SPDX-License-Identifier: MIT-0
---
# vars file for create-instances
resource_group : "rg-k8s-cluster"
location : "eastus"
nsg_name : "nsg-k8s-cluster"
vnet_name : "vnet-k8s-cluster"
vnet_address_prefix : "192.168.0.0/16"
subnet_name : "subnet-k8s-cluster"
subnet_address_prefix : "192.168.1.0/24"

#vms
vm_01 : "instance-01"
vm_02 : "instance-02"
vm_03 : "instance-03"


#Nics
nic_instance_01 : "nic-instance-01"
nic_instance_02 : "nic-instance-02"
nic_instance_03 : "nic-instance-03"

#Size
size_instances : "Standard_B2s"
os_image_offer : "UbuntuServer"
os_image_publisher : "Canonical"
os_image_sku : "24.04-LTS"


#USer
admin_user : "rafaeladmin"
admin_password : "YourP@ssw0rd1234" 