---

- name: Main Playbook
  hosts: all
  roles:
    - role: system-update
      tags: update
    #- role: /tmp/install-packages
    - role: nginx
      tags: nginx
    - role: lab-windows
    - role: IIS
    - role: lab-windows
    - role: create-vm-esxi


