#SPDX-License-Identifier: MIT-0
# tasks file for install-apps
- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - packages