---

- name: Udate debian cache
  ansible.builtin.apt:
    update_cache: yes
  #when: ansible_os_family == "Debian"

- name: Update System
  ansible.builtin.apt:
    name: "*"
    state: latest
  #when: ansible_os_family == "Debian"
