- name: Get IP address
  ansible.windows.win_shell: |
    $ip = (Get-VMNetworkAdapter -VMName "{{ vm_name }}").IPAddresses |
      Where-Object { $_ -match '^192\.168\.40\.' } |
      Select-Object -First 1

    Write-Output $ip
  register: vm_ip

  retries: 20
  delay: 15
  until: vm_ip.stdout != ""

- name: show ip
  debug:
    var: vm_ip.stdout



- name: Ensure guest group exists in inventory
  lineinfile:
    path: "{{ playbook_dir }}/inventory-created.ini"
    line: "[created_vms]" 
    create: yes
    state: present
  delegate_to: localhost

- name: Add vm to inventory
  lineinfile:
    path: "{{ playbook_dir }}/inventory-created.ini"
    insertafter: '^\[created_vms\]$'
    line: " {{ vm_name }} ansible_host={{ vm_ip.stdout | trim }}"
    state: present
  delegate_to: localhost


- name: Add vm to runtime inventory
  add_host:
    name: "{{ vm_name }}"
    groups: created_vms
    ansible_host: "{{ vm_ip.stdout | trim }}"