#SPDX-License-Identifier: MIT-0
---
# handlers file for lab-windows
- name: Restart IIS
  ansible.builtin.win_service:
    name: w3svc
    state: restarted
  
- name: Restart windows
  ansible.windows.win_reboot:
    msg: "Rebooting the system to apply changes"
    pre_reboot_delay: 10
    post_reboot_delay: 30
    reboot_timeout: 600
  when: ansible_facts['os_family'] == 'Windows'
  register: reboot_result

