#SPDX-License-Identifier: MIT-0
---
# vars file for nginx
nginx_package_name: nginx
nginx_service_name: nginx
nginx_conf_dir: /etc/nginx
nginx_sites_available: /etc/nginx/sites-available
nginx_sites_enabled: /etc/nginx/sites-enabled

nginx_sites:
  - server_name: rafaelmellonh.com.br
    listen: "80 default_server"
    root: /var/www/rafaelmellonh.com.br/html
    index: index.html
    location_try_files: "$uri $uri/ /index.html"
    extra_parameters: ""

nginx_firewall_enabled: true