---
- name: Update Linux Server - Ubuntu
  hosts: debian
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags: update

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      tags: 
      -  nginx
      -  httpd