- name: Create NSG
  local_action: 
    module: azure_rm_networksecuritygroup
    resource_group: "{{  }}"
    name: "{{ nsg_name }}"
    location: "{{ location }}"
    rules:
      - name: AllowSSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound

      - name: AllowK8sAPI
        protocol: Tcp
        destination_port_range: 6443
        access: Allow
        priority: 1002
        direction: Inbound
  register: nsg


- name: Create Virtual Network
  local_action:
    module: azure_rm_virtualnetwork
    resource_group: "{{ resource_group }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_address_prefix }}"
    location: "{{ location }}"
    dns_servers: []
    subnets:
      - name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_address_prefix }}"
        network_security_group: "{{ nsg_name }}"
  register: vnet