---
- name: Create resource_group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
  delegate_to: localhost
  run_once: true
  register: rg
  tags: k8s_cluster