--- 
- name: Create an directory
  hosts: debian
  become: yes
  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: "/tmp/ansible_directory"
        state: directory
        mode: '0755'
        owner: rafael
        group: rafael
      tags: create_directory