---
- name: Configure windows
  hosts: all
  vars_files:
    - vars.yaml
  tasks:
    - name: Rename computer
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName {{ name_vm03 }} -Force -restart

    - name: Set timezone
      win_timezone:
        timezone: Eastern Standard Time
    
    - name: Create user
      win_user:
        name: "{{ user_admin }}"
        password: "{{ user_password }}"
        state: present
        groups: Administrators

    - name: Create folder
      win_file:
        name: "{{ directory }}"
        state: directory

    - name: Install win_updates
      win_updates:
        category_names: SecurityUpdates
        state: installed
        reboot: yes
        log_path: "{{ directory }}/wu.log"

    - name: Join domain
      microsoft.ad.membership:
        dns_domain_name: "{{ dns_domain_name }}"
        hostname: "{{ name_vm03 }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_ou_path: "{{ domain_ou_path }}"
        state: domain
        reboot: true