---
- name: Install IIS
  hosts: all
  tasks:
    - name: Install IIS
      win_feature:
        name: 
        - Web-Server
        - Web-Mgmt-tools
        - Web-Mgmt-Console
        state: present
        include_management_tools: yes
       
    - name: Remove Default Web Site
      win_iis_website:
        name: Default Web Site
        state: absent

    - name: Create directory
      win_file:
        path: C:\inetpub\wwwroot\teste
        state: directory
        recurse: yes
    
    - name: Create index.html
      win_copy:
        src: /home/rafael/index.html
        dest: C:\inetpub\wwwroot\teste\index.html

    - name: Create site
      win_iis_website:
        name: teste
        state: started
        physical_path: C:\inetpub\wwwroot\teste
        port: 80
        ip: "*"
        host_header: "teste"
