---
- name: Listar VMs no Hyper-V
  hosts: windows
  vars_files:
    - vars.yaml
  tasks:
    - name: Obter lista de VMs
      ansible.windows.win_powershell:
        script: |
          restart-vm {{ nome_vm }} -force